### PR TITLE
avoid importing kjua on the server platform

### PR DESCRIPTION
**Pull request by takahser**
fixed errors à la “ReferenceError: window is not defined“ and “ReferenceError: document is not defined“

### CODE REVIEW

**Comment by takahser** [comment]
Fixes https://github.com/werthdavid/ngx-kjua/issues/2

The idea here is to avoid importing the kjua library on the server platform, as it is used in angular universal for server-side rendering. This is achieved by using the `isPlatformServer(this.platformId)` method, which is part of the `@angular/common` module.

I tested the fix and it worked for me.
Let me know, if you have any questions or critics. 😄👍🏼

**Comment by werthdavid** [comment]
Looks good so far, thank you! I'll test it with client-side angular and if it works I'll merge an release it

**Comment by werthdavid** [comment]
Now I can't get it running in Browser 😕

**Comment by takahser** [comment]
Sorry, I only tested the npm package, not the project itself!
However, I was able to fix the error.
For the record, I tested the following:

1. angular app: `ng serve`
2. building and using the npm package: `ng build && cd ./dist && npm pack` => registered the resulting tarball in the package.json of the depending project
3. specs: `ng test`

I hope I didn't forget anything :)

**Comment by werthdavid** [comment]
Looks good, thanks for the effort!!

**Pull request merged**
